# render.yaml - Final Corrected Version

# Defines the managed database service first
databases:
  - name: business-db
    plan: free # Use the free tier for your database
    databaseName: business_db # The name of the database inside the instance
    user: db_user # The username for the database

# Defines the web services that will use the database
services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      # These environment variables connect your PHP app to the database
      - key: DB_HOST
        fromDatabase:
          name: business-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: business-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: business-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: business-db
          property: database
      # This environment variable tells your API the frontend's live URL for CORS
      - key: FRONTEND_URL
        fromService:
          name: inventory-frontend
          property: url