# render.yaml - Correct plan configuration

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    # plan: free <-- REMOVED: Static sites are free by default and don't need a plan.
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free # <-- KEPT: This is required for the Docker web service.
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false