# render.yaml - Final attempt with explicit root directories

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    rootDir: inventory-frontend
    # preBuildCommand will help debug by showing what files are present
    preBuildCommand: ls -la
    buildCommand: npm install && npm run build
    publishDirectory: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false