# render.yaml - Explicitly setting the free plan

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    plan: free # <-- ADD THIS LINE
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free # <-- ADD THIS LINE
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false