services:
  # 1. The MySQL Database Service
  - type: pserv
    name: business-db
    runtime: mysql
    region: singapore

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL # This key is required by many frameworks
        fromService:
          type: pserv
          name: business-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: inventory-frontend
          property: url

  # 3. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html