# render.yaml - Corrected Configuration

services:
  # 1. The MySQL Database Service
  - type: pserv
    name: business-db
    runtime: mysql
    region: singapore

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDirectory: inventory-api
    healthCheckPath: /
    envVars:
      - fromService:
          type: pserv
          name: business-db
          envVarKey: DATABASE_URL
      - key: FRONTEND_URL
        value: ${{services.inventory-frontend.url}}

  # 3. The React Frontend Service (CORRECTED)
  - type: web # <-- CHANGE: Type is 'web'
    name: inventory-frontend
    runtime: static # <-- CHANGE: Runtime is 'static'
    region: singapore
    rootDirectory: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build # <-- CHANGE: Use 'staticPublishPath'
    # Rewrite rule for client-side routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html