# render.yaml - Final Configuration with buildFilter

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    # buildFilter explicitly sets the root directory for monorepos.
    buildFilter:
      paths:
      - inventory-frontend/**
      ignoredPaths:
      - inventory-api/**
    buildCommand: npm install && npm run build
    publishDirectory: build

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false