# render.yaml - Corrected with rootDir

services:
  # 1. The MySQL Database Service
  - type: pserv
    name: business-db
    runtime: mysql
    region: singapore

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDir: inventory-api # <-- CORRECTED
    healthCheckPath: /
    envVars:
      - fromService:
          type: pserv
          name: business-db
          envVarKey: DATABASE_URL
      - key: FRONTEND_URL
        value: ${{services.inventory-frontend.url}}

  # 3. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    region: singapore
    rootDir: inventory-frontend # <-- CORRECTED
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html