# render.yaml - Using an external Neon database

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      # This key will now hold the connection string from Neon
      - key: DATABASE_URL
        # Set this to 'sync: false' so it doesn't get overwritten
        sync: false