# render.yaml - Final build path correction

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    # rootDir is removed. The buildCommand now controls the directory.
    buildCommand: cd inventory-frontend && npm install && npm run build
    # The publish directory is relative to the repository root.
    publishDirectory: inventory-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free
    runtime: docker
    region: singapore
    rootDir: inventory-api # rootDir is correct for Docker services
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false