# render.yaml - Final Diagnostic Version

services:
  # 1. The React Frontend Service - SIMPLIFIED FOR DEBUGGING
  - type: web
    name: inventory-frontend
    runtime: static
    # This command will run from the root and list every file and folder
    buildCommand: ls -lR
    # We expect this to fail, but it will give us the file paths we need
    publishDirectory: .

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    plan: free
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false