# render.yaml - Final Version with envVar Fix

databases:
  - name: business-db
    plan: free
    databaseName: business_db
    user: db_user

services:
  # 1. The React Frontend Service
  - type: web
    name: inventory-frontend
    runtime: static
    rootDir: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. The PHP Backend API Service
  - type: web
    name: inventory-api
    runtime: docker
    region: singapore
    rootDir: inventory-api
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: business-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: business-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: business-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: business-db
          property: database
      # --- CORRECTED BLOCK ---
      - key: FRONTEND_URL
        fromService:
          type: web # <-- FIX: Added the required 'type'
          name: inventory-frontend
          property: url 